# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "master", "Branch_openssl-3.*" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

  RELEASE_VERSION: "3.5.4"

  APPLY_VSVARS: 'C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvarsarm64.bat'
  MSVCTargetBuildToolsBin: 'C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.44.35207/bin/HostARM64/arm64'

permissions:
  contents: write # allows the action to create a release. For more information, see [Permissions required for GitHub Apps](https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-contents).

jobs:
  world:
    runs-on: windows-11-arm

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - uses: actions/checkout@v5.0.0
      name: Toolings checkout
      with:
        repository: psqlodbc-for-win10-arm64/Toolings
        path: ToolingsGitRoot

    - name: Toolings Restore dependencies
      working-directory: ToolingsGitRoot
      run: dotnet restore

    - name: Toolings Build
      working-directory: ToolingsGitRoot
      run: dotnet build --no-restore

    - uses: actions/checkout@v5.0.0
      name: PgBuilder checkout
      with:
        repository: psqlodbc-for-win10-arm64/PgBuilder
        path: PgBuilderGitRoot

    - name: PgBuilder Restore dependencies
      working-directory: PgBuilderGitRoot
      run: dotnet restore

    - name: PgBuilder Build
      working-directory: PgBuilderGitRoot
      run: dotnet build --no-restore

    - name: Build OpenSSL Arm64X binaries
      working-directory: PgBuilderGitRoot/PgBuilder
      shell: cmd
      run: |
        dotnet run -- openssl-arm64x-prepare ^
         --alt-cc "%GITHUB_WORKSPACE%/ToolingsGitRoot/Arm64XDualObjCL/bin/Debug/net8.0-windows/Arm64XDualObjCL.exe" ^
         --alt-ld "%GITHUB_WORKSPACE%/ToolingsGitRoot/Arm64XDualObjLINK/bin/Debug/net8.0-windows/Arm64XDualObjLINK.exe" ^
         --alt-ar "%GITHUB_WORKSPACE%/ToolingsGitRoot/Arm64XDualObjLIB/bin/Debug/net8.0-windows/Arm64XDualObjLIB.exe" ^
         "%GITHUB_WORKSPACE%"

        call "%APPLY_VSVARS%"

        dotnet run -- openssl-arm64x-build ^
         --vc-cl   "%MSVCTargetBuildToolsBin%/cl.exe" ^
         --vc-link "%MSVCTargetBuildToolsBin%/link.exe" ^
         --vc-lib  "%MSVCTargetBuildToolsBin%/lib.exe" ^
         "%GITHUB_WORKSPACE%" ^
         "%GITHUB_WORKSPACE%/OpenSSL-inst"

    - name: Create gh-release dir
      shell: pwsh
      run: mkdir gh-release

    - name: Make a zip
      working-directory: OpenSSL-inst
      shell: pwsh
      run: |
        7z.exe a -r "${env:GITHUB_WORKSPACE}/gh-release/Win64Arm64XOpenSSL-${env:RELEASE_VERSION}.zip" .

    - name: Make a GitHub Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: v${{ env.RELEASE_VERSION }} (Arm64X)
        workdir: gh-release
        prerelease: true
