# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  world:
    runs-on: windows-11-arm

    steps:
    - uses: actions/checkout@v4

    - name: Setup Perl environment
      uses: shogo82148/actions-setup-perl@v1.36.0
      with:
        distribution: strawberry

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - uses: actions/checkout@v5.0.0
      with:
        repository: psqlodbc-for-win10-arm64/Toolings
        path: ToolingsGitRoot

    - name: Toolings Restore dependencies
      working-directory: ToolingsGitRoot
      run: dotnet restore

    - name: Toolings Build
      working-directory: ToolingsGitRoot
      run: dotnet build --no-restore

    - uses: actions/checkout@v5.0.0
      with:
        repository: psqlodbc-for-win10-arm64/PgBuilder
        path: PgBuilderGitRoot

    - name: PgBuilder Restore dependencies
      working-directory: PgBuilderGitRoot
      run: dotnet restore

    - name: PgBuilder Build
      working-directory: PgBuilderGitRoot
      run: dotnet build --no-restore

    - name: Build OpenSSL Arm64X binaries
      working-directory: PgBuilderGitRoot/PgBuilder
      shell: pwsh
      run: |
        dotnet run -- openssl-arm64x-prepare `
         --alt-cc "${{env.GITHUB_WORKSPACE}}/ToolingsGitRoot/Arm64XDualObjCL/bin/Debug/net8.0-windows/Arm64XDualObjCL.exe" `
         --alt-ld "${{env.GITHUB_WORKSPACE}}/ToolingsGitRoot/Arm64XDualObjLINK/bin/Debug/net8.0-windows/Arm64XDualObjLINK.exe" `
         --alt-ar "${{env.GITHUB_WORKSPACE}}/ToolingsGitRoot/Arm64XDualObjLIB/bin/Debug/net8.0-windows/Arm64XDualObjLIB.exe" `
         "${{env.GITHUB_WORKSPACE}}"

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: where
      run: where cl.exe
